export default function(req, res, next) {
  const redirects = [
    {
      from: "/shop/alfa-romeo", to: "/alfa-romeo"}, {from: "/shop/audi", to: "/audi",}, {from:"/shop/baic", to:"/baic",}, {from:"/shop/bentley", to:"/bentley"},
    {
      from:"/shop/bmw",
      to:"/bmw",
    },
    {
      from:"/shop/buick",
      to:"/buick"
    },
    {
      from:"/shop/brilliance",
      to:"/brilliance",
    },
    {
      from:"/shop/cadillac",
      to:"/cadillac",
    },
    {
      from:"/shop/changan",
      to:"/changan"
    },
    {
      from:"/shop/chery",
      to:"/chery",
    },
    {
      from:"/shop/chevrolet",
      to:"/chevrolet"
    },
    {
      from:"/shop/chrysler",
      to:"/chrysler"
    },
    {
      from:"/shop/citroen",
      to:"/citroen"
    },
    {
      from:"/shop/dodge",
      to:"/dodge",
    },
    {
      from:"/shop/ferrari",
      to:"/ferrari",
    },
    {
      from:"/shop/fiat",
      to:"/fiat",
    },
    {
      from:"/shop/ford",
      to:"/ford",
    },
    {
      from:"/shop/geely",
      to:"/geely",
    },
    {
      from:"/shop/gmc",
      to:"/gmc"
    },
    {
      from:"/shop/haval",
      to:"/haval",
    },
    {
      from:"/shop/honda",
      to:"/honda",
    },
    {
      from:"/shop/hummer",
      to:"/hummer",
    },
    {
      from:"/shop/hyundai",
      to:"/hyundai",
    },
    {
      from:"/shop/infiniti",
      to:"/infiniti",
    },
    {
      from:"/shop/isuzu",
      to:"/isuzu",
    },
    {
      from:"/shop/jac-motors",
      to:"/jac-motors",
    },
    {
      from:"/shop/jaguar",
      to:"/jaguar",
    },
    {
      from:"/shop/jeep",
      to:"/jeep",
    },
    {
      from:"/shop/kia",
      to:"/kia",
    },
    {
      from:"/shop/land-rover",
      to:"/land-rover",
    },
    {
      from:"/shop/lexus",
      to:"/lexus",
    },
    {
      from:"/shop/lifan",
      to:"/lifan",
    },
    {
      from:"/shop/mazda",
      to:"/mazda",
    },
    {
      from:"/shop/mercedes",
      to:"/mercedes-benz",
    },
    {
      from:"/shop/mercury",
      to:"/mercury",
    },
    {
      from:"/shop/maserati",
      to:"/maserati",
    },
    {
      from:"/shop/mini-cooper",
      to:"/mini"
    },
    {
      from:"/shop/mitsubishi",
      to:"/mitsubishi",
    },
    {
      from:"/shop/mg",
      to:"/mg",
    },
    {
      from:"/shop/nissan",
      to:"/nissan",
    },
    {
      from:"/shop/opel",
      to:"/opel",
    },
    {
      from:"/shop/peugeot",
      to:"/peugeot",
    },
    {
      from:"/shop/pontiac",
      to:"/pontiac",
    },
    {
      from:"/shop/porsche",
      to:"/porsche",
    },
    {
      from:"/shop/renault",
      to:"/renault",
    },
    {
      from:"/shop/rolls-royce",
      to:'/rolls-royce',
    },
    {
      from:"/shop/saab",
      to:"/saab",
    },
    {
      from:"/shop/saturn",
      to:"/saturn",
    },
    {
      from:"/shop/scion",
      to:"/scion",
    },
    {
      from:"/shop/smart-car",
      to:"/smart-car",
    },
    {
      from:"/shop/ssangyong",
      to:"/ssangyong",
    },
    {
      from:"/shop/subaru",
      to:"/subaru",
    },
    {
      from:"/shop/suzuki",
      to:"/suzuki",
    },
    {
      from:"/shop/tesla",
      to:"/tesla",
    },
    {
      from:"/shop/toyota",
      to:"/toyota",
    },
    {
      from:"/shop/volkswagen",
      to:"/volkswagen",
    },
    {
      from:"/shop/volvo",
      to:"/volvo",
    },
    {
      from:"/shop/lincoln",
      to:"/lincoln",
    },
    {
      from:"/shop/ram-car",
      to:"/ram",
    },
    {
      from:"/shop/corvette",
      to:"/corvette",
    },

    // categories
    {
      from:"/shop/car-remotes",
      to:"/car-Remotes",
    },
    {
      from:"/shop/remote-shell",
      to:"/remote-shell",
    },
    {
      from:"/shop/lcd-remotes",
      to:"/lcd-remotes",
    },
    {
      from:"/shop/smart-key-box",
      to:"/smart-key-box",
    },
    {
      from:"/shop/transponder-key",
      to:"/transponder-keys",
    },
    {
      from:"/shop/key-shell",
      to:"key-shell",
    },
    {
      from:"/shop/blades",
      to:"/blades",
    },
    {
      from:"/shop/emergency-key-blade",
      to:"/emergency-keys",
    },
    {
      from:"/shop/key-programming-device",
      to:"/key-programming-diagnostics-tools"
    },
    {
      from:"/shop/key-tester",
      to:"/testing-tool",
    },
    {
      from:"/shop/transponders",
      to:"/transponder-chip-coil",
    },
    {
      from:"/shop/remote-replacement-parts",
      to:"/replacement-parts",
    },
    {
      from:"/shop/garage-gate-remote",
      to:"/garage-gate-remote",
    },
    {
      from:"/shop/emulators",
      to:"/emulators",
    },
    {
      from:"/shop/key-cutting-machine",
      to:"/key-cutting-machine",
    },
    {
      from:"/shop/immobilizer",
      to:"/immobilizer-smart-box"
    },
    {
      from:"/shop/Adapter",
      to:"/adapter",
    },
    {
      from:"/shop/cable",
      to:"/cables",
    },
    {
      from:'/shop/pincode-calculators',
      to:'/pincode-calculators',
    },
    {
      from:"/shop/smart-watch",
      to:"/Watches-Remote",
    },
    {
      from:"/shop/soldering-tool",
      to:"/soldering-tools",
    },
    {
      from:"/shop/eeprom-&-flash",
      to:"/eeprom-flash-and-mcu-chip",
    },
    {
      from:"/shop/motorcycle",
      to:"/motorbike-key"
    },
    {
      from:"/shop/ignitions",
      to:"/ignition-locks",
    },
    {
      from:"/shop/ignition-lock-tools",
      to:"/ignition-lock-cylinder",
    },
    {
      from:"/shop/maintenance-tools",
      to:"/maintenance-tools",
    },
    {
      from:"/shop/steering-lock",
      to:"/steering-lock",
    },
    {
      from:"/shop/spare-parts",
      to:"/spare-parts",
    },
    {
      from:"/shop/battery",
      to:"/battery",
    },
    {
      from:"/shop/TOKEN-KIA-HYUNDAI",
      to:"/pin-code",
    },
    {
      from:"/shop/software",
      to:"/software",
    },
    {
      from:"/shop/ACCESSORIES",
      to:"/accessories-tools",
    },
    // manufactuers
    {
      from:"/shop/advanced-diagnostics",
      to:"/advanced-diagnostics",
    },
    {
      from:"/shop/keyline",
      to:"/keyline",
    },
    {
      from:"/shop/gscan",
      to:"/g-scan",
    },
    {
      from:"/shop/xhorse",
      to:"/xhorse",
    },
    {
      from:"/shop/obdstar",
      to:"/obdstar",
    },
    {
      from:"/shop/scorpio-ik-ltd",
      to:"/scorpio-ik-ltd",
    },
    {
      from:"/shop/orange",
      to:"/orange5",
    },
    {
      from:"/shop/tango",
      to:"/tango",
    },
    {
      from:"/shop/barracuda",
      to:"/barracuda",
    },
    {
      from:"/shop/autohex-ii",
      to:"/autohex-ii",
    },
    {
      from:"/shop/autel",
      to:"/autel",
    },
    {
      from:"/shop/lonsdor",
      to:"/lonsdor",
    },
    {
      from:"/shop/KEYDIY",
      to:"/key-diy-kd",
    },
    {
      from:"/shop/mb-tool",
      to:"/mb-tool",
    },
    {
      from:"/shop/CODE-WIZZARD-PRO-2",
      to:"/code-wizard-pro-2-cwp-2",
    },
    {
      from:"/shop/abrites",
      to:"/abrites",
    },
    {
      from:"/shop/keymax",
      to:"/keymax",
    },
    {
      from:"/shop/XTOOL",
      to:"/XTOOL",
    },
    {
      from:"/shop/strattec",
      to:"/strattec",
    },
    {
      from:"/shop/CG-Automotive-diagnostic",
      to:"/CG-Automotive-diagnostic",
    },
    {
      from:"/shop/raise",
      to:"/raise",
    },
    {
      from:"/shop/lishi",
      to:"/lishi",
    },
    {
      from:"/shop/microtronik",
      to:"/microtronik",
    },
    {
      from:"/shop/eldb",
      to:"/eldb",
    },

  ]
  const redirect = redirects.find((r) => r.from.toLowerCase() === req.url.toLowerCase());

  if (redirect) {
    res.writeHead(301, { Location: redirect.to });
    res.end();
  } else {
    next();
  }
}
