export default function(req, res, next) {
  const redirects = [
    {
      from: "/shop/alfa-romeo", to: "/alfa-romeo"}, {from: "/shop/audi", to: "/audi",}, {from:"/shop/baic", to:"/baic",}, {from:"/shop/bentley", to:"/bentley"},
    {
      from:"/shop/bmw",
      to:"/bmw",
    },
    {
      from:"/shop/buick",
      to:"/buick"
    },
    {
      from:"/shop/brilliance",
      to:"/brilliance",
    },
    {
      from:"/shop/cadillac",
      to:"/cadillac",
    },
    {
      from:"/shop/changan",
      to:"/changan"
    },
    {
      from:"/shop/chery",
      to:"/chery",
    },
    {
      from:"/shop/chevrolet",
      to:"/chevrolet"
    },
    {
      from:"/shop/chrysler",
      to:"/chrysler"
    },
    {
      from:"/shop/citroen",
      to:"/citroen"
    },
    {
      from:"/shop/dodge",
      to:"/dodge",
    },
    {
      from:"/shop/ferrari",
      to:"/ferrari",
    },
    {
      from:"/shop/fiat",
      to:"/fiat",
    },
    {
      from:"/shop/ford",
      to:"/ford",
    },
    {
      from:"/shop/geely",
      to:"/geely",
    },
    {
      from:"/shop/gmc",
      to:"/gmc"
    },
    {
      from:"/shop/haval",
      to:"/haval",
    },
    {
      from:"/shop/honda",
      to:"/honda",
    },
    {
      from:"/shop/hummer",
      to:"/hummer",
    },
    {
      from:"/shop/hyundai",
      to:"/hyundai",
    },
    {
      from:"/shop/infiniti",
      to:"/infiniti",
    },
    {
      from:"/shop/isuzu",
      to:"/isuzu",
    },
    {
      from:"/shop/jac-motors",
      to:"/jac-motors",
    },
    {
      from:"/shop/jaguar",
      to:"/jaguar",
    },
    {
      from:"/shop/jeep",
      to:"/jeep",
    },
    {
      from:"/shop/kia",
      to:"/kia",
    },
    {
      from:"/shop/land-rover",
      to:"/land-rover",
    },
    {
      from:"/shop/lexus",
      to:"/lexus",
    },
    {
      from:"/shop/lifan",
      to:"/lifan",
    },
    {
      from:"/shop/mazda",
      to:"/mazda",
    },
    {
      from:"/shop/mercedes",
      to:"/mercedes-benz",
    },
    {
      from:"/shop/mercury",
      to:"/mercury",
    },
    {
      from:"/shop/maserati",
      to:"/maserati",
    },
    {
      from:"/shop/mini-cooper",
      to:"/mini"
    },
    {
      from:"/shop/mitsubishi",
      to:"/mitsubishi",
    },
    {
      from:"/shop/mg",
      to:"/mg",
    },
    {
      from:"/shop/nissan",
      to:"/nissan",
    },
    {
      from:"/shop/opel",
      to:"/opel",
    },
    {
      from:"/shop/peugeot",
      to:"/peugeot",
    },
    {
      from:"/shop/pontiac",
      to:"/pontiac",
    },
    {
      from:"/shop/porsche",
      to:"/porsche",
    },
    {
      from:"/shop/renault",
      to:"/renault",
    },
    {
      from:"/shop/rolls-royce",
      to:'/rolls-royce',
    },
    {
      from:"/shop/saab",
      to:"/saab",
    },
    {
      from:"/shop/saturn",
      to:"/saturn",
    },
    {
      from:"/shop/scion",
      to:"/scion",
    },
    {
      from:"/shop/smart-car",
      to:"/smart-car",
    },
    {
      from:"/shop/ssangyong",
      to:"/ssangyong",
    },
    {
      from:"/shop/subaru",
      to:"/subaru",
    },
    {
      from:"/shop/suzuki",
      to:"/suzuki",
    },
    {
      from:"/shop/tesla",
      to:"/tesla",
    },
    {
      from:"/shop/toyota",
      to:"/toyota",
    },
    {
      from:"/shop/volkswagen",
      to:"/volkswagen",
    },
    {
      from:"/shop/volvo",
      to:"/volvo",
    },
    {
      from:"/shop/lincoln",
      to:"/lincoln",
    },
    {
      from:"/shop/ram-car",
      to:"/ram",
    },
    {
      from:"/shop/corvette",
      to:"/corvette",
    },

    // categories
    {
      from:"/shop/car-remotes",
      to:"/car-Remotes",
    },
    {
      from:"/shop/remote-shell",
      to:"/remote-shell",
    },
    {
      from:"/shop/lcd-remotes",
      to:"/lcd-remotes",
    },
    {
      from:"/shop/smart-key-box",
      to:"/smart-key-box",
    },
    {
      from:"/shop/transponder-key",
      to:"/transponder-keys",
    },
    {
      from:"/shop/key-shell",
      to:"key-shell",
    },
    {
      from:"/shop/blades",
      to:"/blades",
    },
    {
      from:"/shop/emergency-key-blade",
      to:"/emergency-keys",
    },
    {
      from:"/shop/key-programming-device",
      to:"/key-programming-diagnostics-tools"
    },
    {
      from:"/shop/key-tester",
      to:"/testing-tool",
    },
    {
      from:"/shop/transponders",
      to:"/transponder-chip-coil",
    },
    {
      from:"/shop/remote-replacement-parts",
      to:"/replacement-parts",
    },
    {
      from:"/shop/garage-gate-remote",
      to:"/garage-gate-remote",
    },
    {
      from:"/shop/emulators",
      to:"/emulators",
    },
    {
      from:"/shop/key-cutting-machine",
      to:"/key-cutting-machine",
    },
    {
      from:"/shop/immobilizer",
      to:"/immobilizer-smart-box"
    },
    {
      from:"/shop/Adapter",
      to:"/adapter",
    },
    {
      from:"/shop/cable",
      to:"/cables",
    },
    {
      from:'/shop/pincode-calculators',
      to:'/pincode-calculators',
    },
    {
      from:"/shop/smart-watch",
      to:"/Watches-Remote",
    },
    {
      from:"/shop/soldering-tool",
      to:"/soldering-tools",
    },
    {
      from:"/shop/eeprom-&-flash",
      to:"/eeprom-flash-and-mcu-chip",
    },
    {
      from:"/shop/motorcycle",
      to:"/motorbike-key"
    },
    {
      from:"/shop/ignitions",
      to:"/ignition-locks",
    },
    {
      from:"/shop/ignition-lock-tools",
      to:"/ignition-lock-cylinder",
    },
    {
      from:"/shop/maintenance-tools",
      to:"/maintenance-tools",
    },
    {
      from:"/shop/steering-lock",
      to:"/steering-lock",
    },
    {
      from:"/shop/spare-parts",
      to:"/spare-parts",
    },
    {
      from:"/shop/battery",
      to:"/battery",
    },
    {
      from:"/shop/TOKEN-KIA-HYUNDAI",
      to:"/pin-code",
    },
    {
      from:"/shop/software",
      to:"/software",
    },
    {
      from:"/shop/ACCESSORIES",
      to:"/accessories-tools",
    },
    // manufactuers
    {
      from:"/shop/advanced-diagnostics",
      to:"/advanced-diagnostics",
    },
    {
      from:"/shop/keyline",
      to:"/keyline",
    },
    {
      from:"/shop/gscan",
      to:"/g-scan",
    },
    {
      from:"/shop/xhorse",
      to:"/xhorse",
    },
    {
      from:"/shop/obdstar",
      to:"/obdstar",
    },
    {
      from:"/shop/scorpio-ik-ltd",
      to:"/scorpio-ik-ltd",
    },
    {
      from:"/shop/orange",
      to:"/orange5",
    },
    {
      from:"/shop/tango",
      to:"/tango",
    },
    {
      from:"/shop/barracuda",
      to:"/barracuda",
    },
    {
      from:"/shop/autohex-ii",
      to:"/autohex-ii",
    },
    {
      from:"/shop/autel",
      to:"/autel",
    },
    {
      from:"/shop/lonsdor",
      to:"/lonsdor",
    },
    {
      from:"/shop/KEYDIY",
      to:"/key-diy-kd",
    },
    {
      from:"/shop/mb-tool",
      to:"/mb-tool",
    },
    {
      from:"/shop/CODE-WIZZARD-PRO-2",
      to:"/code-wizard-pro-2-cwp-2",
    },
    {
      from:"/shop/abrites",
      to:"/abrites",
    },
    {
      from:"/shop/keymax",
      to:"/keymax",
    },
    {
      from:"/shop/XTOOL",
      to:"/XTOOL",
    },
    {
      from:"/shop/strattec",
      to:"/strattec",
    },
    {
      from:"/shop/CG-Automotive-diagnostic",
      to:"/CG-Automotive-diagnostic",
    },
    {
      from:"/shop/raise",
      to:"/raise",
    },
    {
      from:"/shop/lishi",
      to:"/lishi",
    },
    {
      from:"/shop/microtronik",
      to:"/microtronik",
    },
    {
      from:"/shop/eldb",
      to:"/eldb",
    },

    //downloads
    {
      from:"/download-files.php?device=AD100Pro",
      to:"/downloads/AD-Loader-AD100-Advanced-Diagnostics-Download-and-Installation",
    },
    {
      from:"/downloads/autohex.php",
      to:"/downloads/Microtronik-Autohex-II"
    },
    {
      from:"/downloads/xhorse.php",
      to:"/downloads/xhorse-vvdi-mb"
    },
    {
      from:"/downloads//vvdi-prog.php",
      to:"/downloads/Xhorse-VVDI-PROG-Programmer-Update-Software-Download",
    },
    {
      from:"/downloads/vvdi-prog.php",
      to:"/downloads/Xhorse-VVDI-PROG-Programmer-Update-Software-Download",
    },
    {
      from:"/downloads//vvdi-2.php",
      to:"/downloads/Xhorse-VVDI2-Key-Programmer",
    },
    {
      from:"/downloads/vvdi-2.php",
      to:"/downloads/Xhorse-VVDI2-Key-Programmer",
    },
    {
      from:"/download-files.php?device=CGGDI-BMW",
      to:"/downloads/CGDI-BMW-Software-Download-Installation"
    },
    {
      from:"/download-files.php?device=TMPRO",
      to:"/downloads/TMPRO",
    },
    {
      from:"/download-files.php?device=KTM-FLASH",
      to:"/downloads/KT200"
    },
    {
      from:"/download-files.php?device=KT200",
      to:"/downloads/KT200"
    },
    {
      from:"/download-files.php?device=Tango",
      to:'/downloads/tango-key-programmer'
    },
    {
      from:"/download-files.php?device=G-scan",
      to:"/downloads/G-Scan",
    },
    {
      from:"/download-files.php?device=gscan-tab",
      to:"/downloads/G-Scan-Tab",
    },
    {
      from:"/download-files.php?device=Orange-5",
      to:"/downloads/Orange-5",
    },
    {
      from:"/download-files.php?device=pin-code",
      to:"/downloads/Diagcode",
    },
    {
      from:"/download-files.php?device=CodeWizardPro",
      to:"/downloads/Diagcode",
    },
    {
      from:"/download-files.php?device=Barracuda",
      to:"/downloads/scorpio-lk-barracuda-key-programmer",
    },
    {
      from:"/download-files.php?device=xhorse",
      to:"/downloads/xhorse-tool-software-download-and-Upgrade-kit",
    },
    {
      from:"/download-files.php?device=xprog",
      to:"/downloads/Xhorse-VVDI-PROG-Programmer-Update-Software-Download"
    },
    {
      from:"/download-files.php?device=vvdi-bimtool",
      to:"/downloads/Xhorse-VVDI-BIMTool-Software-Download-And-Installation",
    },
    {
      from:"/download-files.php?device=AT200",
      to:"/downloads/AT-200",
    },
    {
      from:"/download-files.php?device=pcmtuner",
      to:"/downloads/PCMtuner",
    },
    {
      from:"/download-files.php?device=FC200",
      to:"/downloads/FC200",
    },
    {
      from:"/download-files.php?device=keydiy-download",
      to:"/downloads/keydiy",
    },
    {
      from:"/download-files.php?device=XP400",
      to:"/downloads/XP400-pro",
    },
    {
      from:"/download-files.php?device=SKP900",
      to:"/downloads/SKP-900",
    },
    {
      from:"/download-files.php?device=CG-MB",
      to:"/downloads/CG-MB",
    },
    {
      from:"/download-files.php?device=CG-PRO",
      to:"/downloads/CG-PRO",
    },
    {
      from:"/download-files.php?device=CG100x",
      to:"/downloads/CG100X",
    },
    {
      from:"/download-files.php?device=X100-PRO",
      to:"/downloads/X100-PRO",
    },
    {
      from:"/download-files.php?device=MVCI-PRO",
      to:"/downloads/MVCI-PRO",
    },
    {
      from:"/download-files.php?device=HTProg",
      to:"/downloads/HTProg",
    },
    {
      from:"/download-files.php?device=vvdi-mb",
      to:"/downloads/xhorse-vvdi-mb"
    },
    {
      from:"/products/Chevrolet-2017-Proximity-Flip-Key-5B-433mhz-Aftermarket-Bran-33079",
      to:"/products/Chevrolet-2017-Proximity-Flip-Key-13531362-5B-433mhz-33079"
    },
    {
      from:"/products/Original-Nissan-2013-2018-Flip-Key-3-Buttons-433MHz-H0561-4CA0B-40231",
      to:"/products/Original-Nissan-Sunny-2018-2024-Flip-Key-3-Buttons-433MHz-40231"
    },
    {
      from:"/products/Original-Ford-F-150-2017-Smart-Key-Remote-3-Buttons-868MHz-ID49-Chip-GB5T-15K601-DB-36157",
      to:"/products/SUNSHINE-LC-AD15-Infrared-Thermal-Imaging-Analyzing-Camera-400W-3D-36157"
    },
    {
      from:"/products/Lonsdor-Toyota-Corolla-LT30-01-Universal-Smart-Key-Board-4-Buttons",
      to:"/products/lonsdor-lt30-01-4a-universal-smart-remote-pcb"
    },


  ]
  const redirect = redirects.find((r) => r.from.toLowerCase() === req.url.toLowerCase());

  if (redirect) {
    res.writeHead(301, { Location: redirect.to });
    res.end();
  } else {
    next();
  }
}
